# Generated by Django 4.0.4 on 2022-05-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extractdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='filedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=255)),
                ('service_type_name', models.CharField(max_length=300)),
                ('letter_type_name', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=300)),
                ('middle_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('country_name', models.CharField(max_length=300)),
            ],
        ),
    ]
